const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=v=>"NPR "+Number(v||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});

export function openInvoice(order){
  const d=order?.invoice_data;
  if(!d){alert("Invoice is not available for this order yet.");return}
  if(!["shipped","delivered"].includes(String(order.order_status||"").toLowerCase())){
    alert("Invoice becomes available after the order is shipped.");return
  }
  const items=Array.isArray(d.items)?d.items:[];
  const seller=d.seller||{},buyer=d.buyer||{};
  const rows=items.map((i,n)=>`<tr><td>${n+1}</td><td><strong>${esc(i.product_name||"Product")}</strong><small>${esc([i.product_code,i.color,i.size].filter(Boolean).join(" · "))}</small></td><td>${esc(i.quantity)}</td><td>${money(i.unit_price)}</td><td>${money(i.total_price)}</td></tr>`).join("");
  const vatRegistered=!!d.vat_registered;
  const html=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(d.invoice_number||"Invoice")}</title><style>
  *{box-sizing:border-box}body{margin:0;background:#f5f2ef;color:#211915;font-family:Arial,Helvetica,sans-serif}.sheet{width:min(900px,100%);margin:24px auto;background:#fff;padding:42px;box-shadow:0 8px 35px rgba(0,0,0,.08)}header{display:flex;justify-content:space-between;gap:24px;border-bottom:2px solid #211915;padding-bottom:22px;margin-bottom:24px}.brand h1{margin:0 0 8px;font-size:28px}.brand p,.meta p{margin:3px 0;color:#5e534d;font-size:13px}.meta{text-align:right}.meta h2{margin:0 0 10px;font-size:22px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:26px}.box h3{font-size:12px;text-transform:uppercase;letter-spacing:.08em;margin:0 0 8px;color:#7a6c64}.box p{margin:4px 0;font-size:14px;line-height:1.45}.box strong{font-size:15px}.items{width:100%;border-collapse:collapse;margin-top:12px}.items th,.items td{padding:11px 9px;border-bottom:1px solid #e4ddd8;text-align:left;font-size:13px;vertical-align:top}.items th{background:#f7f3f0;font-size:12px;text-transform:uppercase}.items td:nth-child(1),.items th:nth-child(1),.items td:nth-child(3),.items th:nth-child(3){text-align:center}.items td:nth-child(4),.items th:nth-child(4),.items td:nth-child(5),.items th:nth-child(5){text-align:right}.items small{display:block;color:#746861;margin-top:4px}.totals{margin:22px 0 0 auto;width:min(360px,100%)}.total-row{display:flex;justify-content:space-between;padding:7px 0;font-size:14px}.grand{border-top:2px solid #211915;margin-top:7px;padding-top:11px;font-size:17px;font-weight:700}.note{margin-top:34px;padding-top:18px;border-top:1px solid #e4ddd8;color:#6c6059;font-size:12px}.signature{margin-top:42px;text-align:right;font-size:13px}.actions{width:min(900px,100%);margin:0 auto 18px;display:flex;justify-content:flex-end;gap:10px}.actions button{border:0;border-radius:8px;padding:10px 16px;cursor:pointer;background:#211915;color:#fff;font-weight:600}.actions button.secondary{background:#fff;color:#211915;border:1px solid #d8cec7}@media print{body{background:#fff}.sheet{margin:0;width:100%;padding:18px;box-shadow:none}.actions{display:none}}@media(max-width:650px){.sheet{padding:22px}.grid{grid-template-columns:1fr}header{display:block}.meta{text-align:left;margin-top:18px}.items{font-size:11px}.items th,.items td{padding:8px 5px}}
  </style></head><body><div class="actions"><button class="secondary" onclick="window.close()">Close</button><button onclick="window.print()">Print / Save PDF</button></div><main class="sheet">
  <header><div class="brand"><h1>${esc(seller.name||"Suru Collection")}</h1><p>${esc(seller.address||"")}</p><p>${esc(seller.phone||"")}${seller.email?" · "+esc(seller.email):""}</p><p><strong>Seller PAN:</strong> ${esc(seller.pan||"Not configured")}</p></div><div class="meta"><h2>${vatRegistered?"TAX INVOICE":"PAN BILL / INVOICE"}</h2><p><strong>Invoice No:</strong> ${esc(d.invoice_number)}</p><p><strong>Transaction Date:</strong> ${esc(new Date(d.transaction_date).toLocaleDateString())}</p><p><strong>Invoice Issue Date:</strong> ${esc(new Date(d.invoice_issue_date).toLocaleDateString())}</p></div></header>
  <div class="grid"><div class="box"><h3>Bill To</h3><p><strong>${esc(buyer.name||"Customer")}</strong></p><p>${esc(buyer.address||"")}</p><p>${esc([buyer.city,buyer.district,buyer.province,buyer.postal_code].filter(Boolean).join(", "))}</p><p>${esc(buyer.phone||"")}${buyer.email?" · "+esc(buyer.email):""}</p>${buyer.pan?`<p><strong>Buyer PAN:</strong> ${esc(buyer.pan)}</p>`:""}</div><div class="box"><h3>Payment</h3><p><strong>Method:</strong> ${esc(d.payment_method||"—")}</p><p><strong>Status:</strong> ${esc(d.payment_status||"—")}</p></div></div>
  <table class="items"><thead><tr><th>S.N.</th><th>Details</th><th>Qty</th><th>Per Unit</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table>
  <div class="totals"><div class="total-row"><span>Subtotal</span><strong>${money(d.subtotal)}</strong></div>${Number(d.shipping_fee||0)?`<div class="total-row"><span>Delivery / Shipping</span><strong>${money(d.shipping_fee)}</strong></div>`:""}${Number(d.discount||0)?`<div class="total-row"><span>Discount</span><strong>- ${money(d.discount)}</strong></div>`:""}${vatRegistered?`<div class="total-row"><span>Taxable Amount</span><strong>${money(d.taxable_amount)}</strong></div><div class="total-row"><span>VAT ${esc(d.vat_rate)}%</span><strong>${money(d.vat_amount)}</strong></div>`:""}<div class="total-row grand"><span>Grand Total</span><strong>${money(d.total)}</strong></div></div>
  <div class="signature">${esc(d.seller_signature||"Authorized Signature")}<br><span>Seller</span></div><div class="note">This invoice was generated from the Suru Collection order record. Please retain this invoice for your records.</div>
  </main></body></html>`;
  const w=window.open("","_blank","noopener,noreferrer");
  if(!w){alert("Please allow pop-ups to view the invoice.");return}
  w.document.write(html);w.document.close();
}
