import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const ROOT="1zeVIdGtmBCianwPQsGxwOkXnqclLapNh", DRIVE="https://www.googleapis.com/drive/v3", TOKEN="https://oauth2.googleapis.com/token", SCOPE="https://www.googleapis.com/auth/drive";
const b64=(b:Uint8Array)=>btoa(String.fromCharCode(...b)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const ub64=(s:string)=>b64(new TextEncoder().encode(s));
function der(pem:string){const normalized=pem.replace(/\\n/g,"\n").replace(/\\r/g,"\r");const clean=normalized.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----/g,"").replace(/\s+/g,"");const binary=atob(clean);return Uint8Array.from(binary,c=>c.charCodeAt(0));}
async function token(){const email=Deno.env.get("GOOGLE_DRIVE_SERVICE_ACCOUNT_EMAIL")?.trim(),pk=Deno.env.get("GOOGLE_DRIVE_SERVICE_ACCOUNT_PRIVATE_KEY")?.trim();if(!email||!pk)throw new Error("Google Drive service-account secrets are not configured.");const now=Math.floor(Date.now()/1000),unsigned=ub64(JSON.stringify({alg:"RS256",typ:"JWT"}))+"."+ub64(JSON.stringify({iss:email,scope:SCOPE,aud:TOKEN,iat:now,exp:now+3600})),key=await crypto.subtle.importKey("pkcs8",der(pk),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]),sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,new TextEncoder().encode(unsigned)),r=await fetch(TOKEN,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion:unsigned+"."+b64(new Uint8Array(sig))})}),p=await r.json().catch(()=>({}));if(!r.ok||!p.access_token)throw new Error("Google authorization failed.");return p.access_token as string;}
async function list(t:string,q:string){const out:any[]=[];let page="";do{const p=new URLSearchParams({q,fields:"files(id,name,mimeType,createdTime,modifiedTime),nextPageToken",pageSize:"1000",supportsAllDrives:"true",includeItemsFromAllDrives:"true",orderBy:"createdTime"});if(page)p.set("pageToken",page);const r=await fetch(DRIVE+"?"+p,{headers:{Authorization:"Bearer "+t}}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x?.error?.message||"Google Drive request failed.");out.push(...(x.files||[]));page=x.nextPageToken||"";}while(page);return out;}
const ok=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
Deno.serve(async req=>{if(req.method!=="POST")return ok({message:"POST required."},405);const sb=createClient(Deno.env.get("SUPABASE_URL")||"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||""),secret=req.headers.get("x-cron-secret")||"",v=await sb.rpc("verify_drive_sync_cron_secret",{p_secret:secret});if(v.error||v.data!==true)return ok({message:"Unauthorized."},401);try{const t=await token(),p=await sb.from("products").select("id,product_code").not("product_code","is",null);if(p.error)throw p.error;const folders=await list(t,"'"+ROOT+"' in parents and mimeType = 'application/vnd.google-apps.folder' and trashed = false"),fm=new Map<string,any>();for(const f of folders){const c=String(f.name||"").trim().toUpperCase();if(/^[A-Z0-9_-]{1,64}$/.test(c)&&!fm.has(c))fm.set(c,f);}let matched=0,images=0,jobs=0;const errors:string[]=[];for(const product of p.data||[]){const code=String(product.product_code||"").trim().toUpperCase(),folder=fm.get(code);if(!folder)continue;matched++;try{const files=(await list(t,"'"+folder.id+"' in parents and mimeType contains 'image/' and trashed = false")).sort((a,b)=>(Date.parse(a.createdTime||"")||0)-(Date.parse(b.createdTime||"")||0)||String(a.name||"").localeCompare(String(b.name||"")));for(const [i,f] of files.entries()){images++;const url=(Deno.env.get("SUPABASE_URL")||"")+"/functions/v1/google-drive-image?id="+encodeURIComponent(f.id),exists=await sb.from("product_images").select("id").eq("product_id",product.id).eq("image_url",url).maybeSingle();if(!exists.data){const ins=await sb.from("product_images").insert({product_id:product.id,image_url:url,alt_text:code,sort_order:i,is_main:i===0});if(ins.error)throw ins.error;}const j=await sb.from("product_image_processing_jobs").upsert({product_id:product.id,product_code:code,source_file_id:f.id,source_file_name:f.name||null,source_mime_type:f.mimeType||null,source_created_at:f.createdTime||null,source_modified_at:f.modifiedTime||null,source_signature:String(f.id)+"|"+String(f.modifiedTime||f.createdTime||"")},{onConflict:"product_id,source_file_id,source_signature",ignoreDuplicates:true});if(j.error)throw j.error;jobs++;}}catch(e){errors.push(code+": "+(e instanceof Error?e.message:"sync failed"));}}return ok({success:true,products:p.data?.length||0,folders_matched:matched,images_discovered:images,jobs_seen_or_queued:jobs,errors});}catch(e){console.error("google-drive-image-sync",e);return ok({success:false,message:e instanceof Error?e.message:"Drive sync failed."},502);}});
