import React,{useEffect,useMemo,useRef,useState} from "react";
import QRCode from "qrcode";
import { supabase, get, money, norm, imageUrl } from "../lib/api.js";
import { readCart, addCart, removeCart, clearCart, cartKey } from "../lib/cart.js";
import { openInvoice, openCustomerInvoice } from "../lib/invoice.js";
import Header from "../components/Header.jsx";
import Footer from "../components/Footer.jsx";
import Hero from "../components/Hero.jsx";
import CollectionCard from "../components/CollectionCard.jsx";
import ProductsGrid from "../components/ProductsGrid.jsx";
import AuthLayout from "../components/AuthLayout.jsx";
import OrderTable from "../components/admin/OrderTable.jsx";
import ProductAdminCard from "../components/admin/ProductAdminCard.jsx";
import StockRow from "../components/admin/StockRow.jsx";
import PreorderAdminQueue from "../components/admin/PreorderAdminQueue.jsx";
import CustomerAddressesPanel from "../components/customer/CustomerAddressesPanel.jsx";
import { SIZE_ORDER,sizeRank,getNcmBranches,ncmNorm,ncmCoords,ncmDistanceKm,ncmFieldTokens,ncmWordMatch,matchNcmBranch,cats,NEPAL_PROVINCES,provinceDistricts,canonicalProvince,offerPasskeyPrompt,normalizeNepalPhone } from "../lib/appShared.js";

function Login(){
 const[method,setMethod]=useState("email"),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const[authChecking,setAuthChecking]=useState(true);
 useEffect(()=>{let active=true;const finish=async session=>{if(!active||!session)return;try{const{data:existing,error:profileError}=await supabase.rpc("my_customer_profile");if(profileError)throw profileError;if(!existing){const user=session.user,m=user.user_metadata||{},fullName=String(m.full_name||m.name||[m.given_name||m.first_name,m.family_name||m.last_name].filter(Boolean).join(" ")||user.email?.split("@")[0]||"Customer").trim(),parts=fullName.split(/\\s+/);const{error}=await supabase.from("customers").upsert({auth_user_id:user.id,name:fullName,first_name:m.given_name||m.first_name||parts[0]||"",last_name:m.family_name||m.last_name||parts.slice(1).join(""),email:user.email||m.email||null,phone:m.phone||"",address:m.address||null,city:m.city||null,district:m.district||null,province:m.province||null,postal_code:m.postal_code||null,is_active:true},{onConflict:"auth_user_id"});if(error)throw error;}if(active)location.replace(returnTo)}catch(error){if(active){setMsg("Signed in, but your customer profile could not be prepared. "+(error?.message||"Please contact support."));setAuthChecking(false)}}};const{data:listener}=supabase.auth.onAuthStateChange((_event,session)=>{if(session)void finish(session)});supabase.auth.getSession().then(({data,error})=>{if(!active)return;if(!error&&data.session){void finish(data.session);return}setAuthChecking(false)});return()=>{active=false;listener.subscription.unsubscribe()}},[]);
 const returnTo=(()=>{const value=new URLSearchParams(location.search).get("return");return value&&value.startsWith("/")&&!value.startsWith("//")?value:"/"})();
 if(authChecking)return <AuthLayout title="Customer Login"><p className="auth-intro">Checking your sign-in status…</p></AuthLayout>;
 async function passkeySignIn(){setBusy(true);setMsg("Waiting for passkey…");const{error}=await supabase.auth.signInWithPasskey();if(error){setMsg(error.message||"Passkey sign-in failed.");setBusy(false);return}location.href=returnTo}
 async function googleSignIn(){setBusy(true);setMsg("Redirecting to Google…");const{error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.origin+"/login/?return="+encodeURIComponent(returnTo)}});if(error){setMsg(error.message||"Google sign-in could not be started.");setBusy(false)}}
 async function sendMagicLink(){if(!email.trim()){setMsg("Enter your email address first.");return}setBusy(true);setMsg("Sending your one-time sign-in link…");const{error}=await supabase.auth.signInWithOtp({email:email.trim().toLowerCase(),options:{emailRedirectTo:location.origin+"/?page=account",shouldCreateUser:false}});setMsg(error?error.message:"If an account exists for that email, a one-time sign-in link has been sent. Check your inbox and spam folder.");setBusy(false)}
 async function submit(e){e.preventDefault();if(!password||(method==="mobile"?!phone:!email)){setMsg(method==="mobile"?"Please enter your mobile number and password.":"Please enter your email and password.");return}let credentials;if(method==="mobile"){const normalizedPhone=normalizeNepalPhone(phone);if(!/^\\+9779\\d{9}$/.test(normalizedPhone)){setMsg("Please enter a valid Nepal mobile number.");return}credentials={phone:normalizedPhone,password}}else{credentials={email:email.trim(),password}}setBusy(true);setMsg("Signing in…");const{data,error}=await supabase.auth.signInWithPassword(credentials);if(error){setMsg(error.message);setBusy(false);return}const{data:profile}=await supabase.rpc("my_customer_profile");if(!profile){const user=data.user;const m=user.user_metadata||{};await supabase.from("customers").upsert({auth_user_id:user.id,name:m.name||"",first_name:m.first_name||"",last_name:m.last_name||"",email:user.email,phone:m.phone||"",address:m.address||null,city:m.city||null,district:m.district||null,is_active:true},{onConflict:"auth_user_id"})}await offerPasskeyPrompt(data.user?.id);location.href=returnTo}
 return <AuthLayout title="Customer Login"><p className="auth-intro">Sign in using your mobile number or email and password.</p><div className="login-method-switch" role="group" aria-label="Login method"><button type="button" className={method==="email"?"active":""} onClick={()=>{setMethod("email");setMsg("")}}>Email Login</button><button type="button" className={method==="mobile"?"active":""} onClick={()=>{setMethod("mobile");setMsg("")}}>Mobile Login</button></div><form onSubmit={submit}>{method==="mobile"?<label className="field">Mobile Number<div className="phone-input-wrap"><span className="phone-country-code">+977</span><input type="tel" value={phone} onChange={e=>setPhone(e.target.value.replace(/\\D/g,"").slice(0,10))} autoComplete="tel-national" inputMode="numeric" maxLength="10" placeholder="10-digit mobile number" required/></div></label>:<label className="field">Email Address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="Enter your email address" required/></label>}<label className="field">Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="btn" disabled={busy}>{busy?"Signing In…":"Sign In"}</button>{msg&&<div className={msg.startsWith("If an account exists")?"message success":"message error"}>{msg}</div>}</form><div className="login-extra-actions">{method==="email"&&<button className="btn secondary" type="button" onClick={sendMagicLink} disabled={busy}>Get One-Time Login Link</button>}<button className="btn secondary" type="button" onClick={passkeySignIn} disabled={busy}>Sign in with a Passkey</button></div><div className="auth-google"><button type="button" className="google-auth-button" onClick={googleSignIn} disabled={busy}><span className="google-g" aria-hidden="true">G</span>Continue with Google</button></div><div className="auth-links">{method==="email"&&<><a href="/?page=reset-password">Forgot password?</a><span aria-hidden="true"> · </span></>}New customer? <a href="register.html">Create an account</a></div></AuthLayout>
}