const client=window.supabase.createClient(window.SURU_SUPABASE_URL,window.SURU_SUPABASE_KEY),$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s),money=n=>'NPR '+Number(n||0).toLocaleString('en-IN'),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c));
function msg(el,text,type=''){el.textContent=text;el.className='message '+type}
async function isAdmin(session){if(!session?.user)return{ok:false,error:'No active session.'};const{data,error}=await client.rpc('is_admin');if(error)return{ok:false,error:'Admin check failed: '+error.message};return{ok:data===true,error:data===true?'':'This account is not authorized for the admin panel.'}}
async function start(sessionOverride=null){try{const sessionResult=sessionOverride?{data:{session:sessionOverride},error:null}:await client.auth.getSession();if(sessionResult.error)throw sessionResult.error;const session=sessionResult.data.session;if(!session){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');return false}const admin=await isAdmin(session);if(!admin.ok){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');msg($('#loginMessage'),admin.error||'Admin authorization failed.','error');return false}$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userEmail').textContent=session.user.email||'';loadDashboard();return true}catch(err){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');msg($('#loginMessage'),'Connection error: '+(err?.message||err),'error');return false}}
client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'||event==='INITIAL_SESSION'||event==='TOKEN_REFRESHED')setTimeout(()=>start(session),0);if(event==='SIGNED_OUT'){ $('#loginView').classList.remove('hidden'); $('#appView').classList.add('hidden'); }});
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;if(!email||!password){msg($('#loginMessage'),'Please enter email and password.','error');return}msg($('#loginMessage'),'Signing in…');const{data,error}=await client.auth.signInWithPassword({email,password});if(error){msg($('#loginMessage'),error.message,'error');return}const ok=await start(data.session);if(ok)$('#loginPassword').value=''});$('#logoutBtn').onclick=async()=>{await client.auth.signOut();location.reload()};
$$('.sidebar button').forEach(b=>b.onclick=()=>{$$('.sidebar button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.view).classList.add('active');({dashboard:loadDashboard,orders:loadOrders,products:loadProducts,inventory:loadInventory,subscribers:loadSubscribers}[b.dataset.view])()});
async function loadDashboard(){const[{count:orders},{count:products},{count:subs},{data:pending}]=await Promise.all([client.from('orders').select('*',{count:'exact',head:true}),client.from('products').select('*',{count:'exact',head:true}).eq('is_active',true),client.from('newsletter_subscribers').select('*',{count:'exact',head:true}).eq('is_active',true),client.from('orders').select('id,order_number,customer_name,total,order_status,created_at').order('created_at',{ascending:false}).limit(5)]);$('#statOrders').textContent=orders??0;$('#statProducts').textContent=products??0;$('#statSubscribers').textContent=subs??0;$('#statPending').textContent=(pending||[]).filter(x=>x.order_status==='pending').length;renderOrderTable($('#recentOrders'),pending||[],false)}
function renderOrderTable(el,rows,full=true){if(!rows.length){el.innerHTML='<p class="subscriber-count">No orders found.</p>';return}el.innerHTML='<table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th><th>Date</th>'+(full?'<th>Update</th>':'')+'</tr></thead><tbody>'+rows.map(o=>`<tr><td><b>${esc(o.order_number)}</b>${full?`<div class="order-items" data-items="${esc(o.id)}"></div>`:''}</td><td>${esc(o.customer_name)}<br><small>${esc(o.customer_phone||'')}</small></td><td>${money(o.total)}</td><td><span class="badge">${esc(o.order_status)}</span></td><td>${new Date(o.created_at).toLocaleString()}</td>${full?`<td><select class="status-select" data-id="${o.id}">${['pending','confirmed','processing','shipped','delivered','cancelled'].map(s=>`<option ${s===o.order_status?'selected':''}>${s}</option>`).join('')}</select></td>`:''}</tr>`).join('')+'</tbody></table>';if(full)loadOrderItems(rows)}
async function loadOrderItems(rows){const ids=rows.map(x=>x.id),{data}=await client.from('order_items').select('order_id,product_name,size,quantity').in('order_id',ids);(data||[]).forEach(i=>{const el=document.querySelector(`[data-items="${i.order_id}"]`);if(el)el.textContent+=(el.textContent?', ':'')+`${i.product_name}${i.size?' ('+i.size+')':''} × ${i.quantity}`})}
async function loadOrders(){const search=$('#orderSearch').value.trim(),status=$('#orderStatusFilter').value;let q=client.from('orders').select('*').order('created_at',{ascending:false}).limit(100);if(status)q=q.eq('order_status',status);if(search)q=q.or(`order_number.ilike.%${search}%,customer_name.ilike.%${search}%,customer_phone.ilike.%${search}%`);const{data,error}=await q;if(error){$('#ordersTable').innerHTML=`<p class="message error">${esc(error.message)}</p>`;return}renderOrderTable($('#ordersTable'),data||[],true)}$('#orderSearch').addEventListener('input',loadOrders);$('#orderStatusFilter').addEventListener('change',loadOrders);
document.addEventListener('change',async e=>{if(!e.target.matches('.status-select'))return;const id=e.target.dataset.id,status=e.target.value;e.target.disabled=true;const{error}=await client.from('orders').update({order_status:status}).eq('id',id);e.target.disabled=false;if(error)alert(error.message)});
async function loadProducts(){const{data,error}=await client.from('products').select('*,product_images(id,image_url,sort_order,is_main)').order('created_at',{ascending:false});if(error){$('#productsGrid').innerHTML=`<p class="message error">${esc(error.message)}</p>`;return}$('#productsGrid').innerHTML='<div class="product-grid">'+(data||[]).map(p=>{const imgs=(p.product_images||[]).slice().sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));return `<div class="product-card-admin"><small>${esc(p.product_code)} · ${esc(p.category)}</small><h3>${esc(p.name)}</h3><label>Price<input type="number" step="0.01" value="${p.price}" data-price="${p.id}"></label><label>MOQ<input type="number" value="${p.moq}" data-moq="${p.id}"></label><label><input type="checkbox" ${p.is_active?'checked':''} data-active="${p.id}"> Active</label><label><input type="checkbox" ${p.is_featured?'checked':''} data-featured="${p.id}"> Featured</label><label>Image URLs <textarea rows="4" data-images="${p.id}" placeholder="One public/direct image URL per line">${esc(imgs.map(x=>x.image_url).join('\n'))}</textarea></label><p class="hint">First URL becomes the main image. Use direct/public image links.</p><button class="primary save-product" data-id="${p.id}">Save Changes</button><span class="message" id="pm-${p.id}"></span></div>`}).join('')+'</div>'}
document.addEventListener('click',async e=>{const b=e.target.closest('.save-product');if(!b)return;const id=b.dataset.id,get=a=>document.querySelector(`[data-${a}="${id}"]`),payload={price:Number(get('price').value),moq:Math.max(0,Number(get('moq').value)),is_active:get('active').checked,is_featured:get('featured').checked};const{error}=await client.from('products').update(payload).eq('id',id);if(error){msg($('#pm-'+id),'Save failed: '+error.message,'error');return}const box=get('images'),urls=box.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const old=await client.from('product_images').select('id').eq('product_id',id);if(old.error){msg($('#pm-'+id),'Product saved, but images could not be read: '+old.error.message,'error');return}if((old.data||[]).length){const d=await client.from('product_images').delete().eq('product_id',id);if(d.error){msg($('#pm-'+id),'Product saved, but old images could not be replaced: '+d.error.message,'error');return}}if(urls.length){const r=await client.from('product_images').insert(urls.map((url,i)=>({product_id:id,image_url:url,sort_order:i,is_main:i===0})));if(r.error){msg($('#pm-'+id),'Product saved, but image URLs failed: '+r.error.message,'error');return}}msg($('#pm-'+id),'Saved','success')});
async function loadInventory(){const{data,error}=await client.from('products').select('id,product_code,name,product_sizes(id,size,stock,is_active)').order('product_code');if(error){$('#inventoryGrid').innerHTML=`<div class="card"><p class="message error">${esc(error.message)}</p></div>`;return}$('#inventoryGrid').innerHTML=(data||[]).map(p=>`<div class="card"><h3>${esc(p.product_code)} — ${esc(p.name)}</h3><div class="stock-list">${(p.product_sizes||[]).map(s=>`<div class="stock-row"><span><b>${esc(s.size)}</b></span><input type="number" min="0" value="${s.stock}" data-stock="${s.id}" data-old="${s.stock}"><button class="primary save-stock" data-id="${s.id}" data-product="${p.id}">Save</button></div>`).join('')||'<p class="subscriber-count">No sizes configured.</p>'}</div></div>`).join('')}
document.addEventListener('click',async e=>{const b=e.target.closest('.save-stock');if(!b)return;const input=document.querySelector(`[data-stock="${b.dataset.id}"]`),old=Number(input.dataset.old),stock=Math.max(0,parseInt(input.value||0,10));const{error}=await client.from('product_sizes').update({stock}).eq('id',b.dataset.id);if(error){alert(error.message);return}const diff=stock-old;if(diff)await client.from('inventory_movements').insert({product_id:b.dataset.product,size_id:b.dataset.id,quantity_change:diff,reason:'admin_stock_adjustment'});input.dataset.old=stock;b.textContent='Saved';setTimeout(()=>b.textContent='Save',1000)});
async function loadSubscribers(){const{data,error}=await client.from('newsletter_subscribers').select('*').order('subscribed_at',{ascending:false});if(error){$('#subscribersTable').innerHTML=`<p class="message error">${esc(error.message)}</p>`;return}$('#subscriberCount').textContent=`${data?.length||0} subscriber${(data?.length||0)===1?'':'s'}`;$('#subscribersTable').innerHTML='<table class="table"><thead><tr><th>Email</th><th>Subscribed</th><th>Status</th><th>Action</th></tr></thead><tbody>'+((data||[]).map(s=>`<tr><td>${esc(s.email)}</td><td>${new Date(s.subscribed_at).toLocaleString()}</td><td>${s.is_active?'Active':'Inactive'}</td><td><button class="${s.is_active?'danger':'secondary'} toggle-sub" data-id="${s.id}" data-active="${s.is_active}">${s.is_active?'Deactivate':'Activate'}</button></td></tr>`).join(''))+'</tbody></table>'}
document.addEventListener('click',async e=>{const b=e.target.closest('.toggle-sub');if(!b)return;const active=b.dataset.active!=='true';const{error}=await client.from('newsletter_subscribers').update({is_active:active}).eq('id',b.dataset.id);if(error)alert(error.message);else loadSubscribers()});start();

function slugify(v){return String(v||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
async function addProduct(e){
 e.preventDefault(); const m=$('#addProductMessage'); msg(m,'Adding product…');
 const code=$('#newCode').value.trim().toUpperCase(), name=$('#newName').value.trim(), category=$('#newCategory').value.trim();
 const payload={product_code:code,name,slug:slugify(code),category,price:Number($('#newPrice').value||0),moq:Math.max(1,parseInt($('#newMoq').value||1,10)),fabric:$('#newFabric').value.trim()||null,color:$('#newColor').value.trim()||null,pattern:$('#newPattern').value.trim()||null,description:$('#newDescription').value.trim()||null,is_active:true,is_featured:false};
 if(!code||!name||!category||!payload.price){msg(m,'Code, name, category and price are required.','error');return}
 const {data:p,error}=await client.from('products').insert(payload).select('id,product_code').single(); if(error){msg(m,'Could not add product: '+error.message,'error');return}
 const urls=$('#newImageUrls').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
 if(urls.length){const rows=urls.map((url,i)=>({product_id:p.id,image_url:url,alt_text:name,sort_order:i,is_main:i===0}));const r=await client.from('product_images').insert(rows);if(r.error){await client.from('products').delete().eq('id',p.id);msg(m,'Product was not saved because image URLs failed: '+r.error.message,'error');return}}
 const sizeLines=$('#newSizes').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean); if(sizeLines.length){const rows=sizeLines.map(line=>{const a=line.split('|').map(x=>x.trim());return {product_id:p.id,size:a[0],bust:a[1]?Number(a[1]):null,waist:a[2]?Number(a[2]):null,hip:a[3]?Number(a[3]):null,shoulder:a[4]?Number(a[4]):null,top_length:a[5]?Number(a[5]):null,bottom_length:a[6]?Number(a[6]):null,dupatta_length:a[7]?Number(a[7]):null,unit:'inches',stock:a[8]?Math.max(0,parseInt(a[8],10)):0,is_active:true}}).filter(x=>x.size);const r=await client.from('product_sizes').insert(rows);if(r.error){msg(m,'Product added, but sizes failed: '+r.error.message,'error');}else msg(m,'Product added successfully.','success')}else msg(m,'Product added successfully.','success');
 $('#addProductForm').reset(); $('#newMoq').value=1; loadProducts(); loadInventory();
}
$('#addProductForm')?.addEventListener('submit',addProduct);

