import React,{useEffect,useMemo,useState} from "react";
import{createRoot}from"react-dom/client";
import"./styles.css";
import { supabase, get, money, norm } from "./lib/api.js";
import { readCart, addCart, removeCart, clearCart } from "./lib/cart.js";
import Header from "./components/Header.jsx";
import Footer from "./components/Footer.jsx";
import Hero from "./components/Hero.jsx";
import CollectionCard from "./components/CollectionCard.jsx";
import ProductsGrid from "./components/ProductsGrid.jsx";
import AuthLayout from "./components/AuthLayout.jsx";
import OrderTable from "./components/admin/OrderTable.jsx";
import ProductAdminCard from "./components/admin/ProductAdminCard.jsx";
import StockRow from "./components/admin/StockRow.jsx";

const cats=[["cat-sarees.jpg","Sarees","Elegant drapes for every occasion."],["cat-lehengas.jpg","Lehengas","Festive looks with timeless charm."],["cat-suits.jpg","Suits","Classic ethnic styles for every day."],["cat-gowns.jpg","Gowns","Graceful styles for special moments."],["cat-kurtis.jpg","Kurtis","Beautiful comfort for everyday elegance."],["cat-dupatta.jpg","Dupattas","Finishing touches that complete the look."],["cat-accessories.jpg","Accessories","Details that add a little more sparkle."]];
function Login(){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session)location.href="account.html"})},[]);
 async function submit(e){e.preventDefault();if(!email||!password){setMsg("Please enter your email and password.");return}setBusy(true);setMsg("Signing in…");const{data,error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error){setMsg(error.message);setBusy(false);return}const{data:profile}=await supabase.rpc("my_customer_profile");if(!profile){const user=data.user;const m=user.user_metadata||{};await supabase.from("customers").upsert({auth_user_id:user.id,name:m.name||"",email:user.email,phone:m.phone||"",address:m.address||null,city:m.city||null,district:m.district||null,is_active:true},{onConflict:"auth_user_id"})}location.href="account.html"}
 return <AuthLayout title="Customer Login"><p className="auth-intro">Sign in using your email and password.</p><form onSubmit={submit}><label className="field">Email Address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/></label><label className="field">Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="btn" disabled={busy}>{busy?"Signing In…":"Sign In"}</button>{msg&&<div className="message error">{msg}</div>}</form><div className="auth-links">New customer? <a href="register.html">Create an account</a></div></AuthLayout>
}
function Register(){
 const[f,setF]=useState({name:"",email:"",password:"",confirm:"",phone:"",address:"",city:"",district:""}),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const change=e=>setF({...f,[e.target.name]:e.target.value});
 async function submit(e){e.preventDefault();if(f.password.length<6)return setMsg("Password must be at least 6 characters.");if(f.password!==f.confirm)return setMsg("Passwords do not match.");if(!f.phone.trim())return setMsg("Please enter your phone number.");setBusy(true);setMsg("Creating your account…");const{data,error}=await supabase.auth.signUp({email:f.email.trim().toLowerCase(),password:f.password,options:{data:{name:f.name,phone:f.phone,address:f.address,city:f.city,district:f.district}}});if(error){setMsg(error.message);setBusy(false);return}if(!data?.session){setMsg('Your account was created, but email confirmation is still enabled in Supabase.');setBusy(false);return}const{error:profileError}=await supabase.from("customers").upsert({auth_user_id:data.user.id,name:f.name,email:f.email.trim().toLowerCase(),phone:f.phone,address:f.address||null,city:f.city||null,district:f.district||null,is_active:true},{onConflict:"auth_user_id"});if(profileError){setMsg(profileError.message);setBusy(false);return}location.href="account.html"}
 return <AuthLayout title="Create Account"><p className="auth-intro">Create your account with email and password. Phone number is required for delivery/contact.</p><form onSubmit={submit}>{[["name","Full Name","text"],["email","Email Address","email"],["password","Password","password"],["phone","Phone Number","tel"],["confirm","Confirm Password","password"]].map(([n,l,t])=><label className="field" key={n}>{l}<input name={n} type={t} value={f[n]} onChange={change} required={n!=="confirm"||true} autoComplete={n==="email"?"email":n==="phone"?"tel":"off"}/></label>)}<label className="field">Delivery Address<textarea name="address" rows="3" value={f.address} onChange={change}/></label><label className="field">City<input name="city" value={f.city} onChange={change}/></label><label className="field">District<input name="district" value={f.district} onChange={change}/></label><button className="btn" disabled={busy}>{busy?"Creating…":"Create Account"}</button>{msg&&<div className="message error">{msg}</div>}</form><div className="auth-links">Already have an account? <a href="login.html">Sign in</a></div></AuthLayout>
}
function Account(){
 const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[orders,setOrders]=useState([]),[msg,setMsg]=useState(""),[busy,setBusy]=useState(true);
 useEffect(()=>{(async()=>{const{data}=await supabase.auth.getSession();if(!data.session){location.href="login.html";return}setSession(data.session);let{data:p}=await supabase.rpc("my_customer_profile");if(typeof p==="string"){try{p=JSON.parse(p)}catch{}}if(!p){const{data:direct}=await supabase.from("customers").select("*").eq("auth_user_id",data.session.user.id).maybeSingle();p=direct}setProfile(p||null);if(p){const{data:o}=await supabase.from("orders").select("id,order_number,total,payment_method,payment_status,order_status,shipping_address,city,created_at,order_items(product_name,size,color,quantity,unit_price,total_price)").eq("customer_id",p.id).order("created_at",{ascending:false});setOrders(o||[])}setBusy(false)})()},[]);
 async function save(e){e.preventDefault();if(!profile.phone?.trim()||!profile.name?.trim()){setMsg("Name and phone number are required.");return}setMsg("Saving…");const{data,error}=await supabase.from("customers").update({name:profile.name,phone:profile.phone,address:profile.address||null,city:profile.city||null,district:profile.district||null,updated_at:new Date().toISOString()}).eq("auth_user_id",session.user.id).select().maybeSingle();setMsg(error?error.message:"Account details saved successfully.");if(data)setProfile(data)}
 async function logout(){await supabase.auth.signOut();location.href="login.html"}
 if(busy)return <><Header/><main className="page"><section className="account-card"><div className="product-loading">Loading account…</div></section></main><Footer/></>;
 if(!profile)return <><Header/><main className="page"><section className="account-card"><h1>Welcome, Customer</h1><div className="message error">Your login is active, but your customer profile could not be found.</div><button className="btn secondary" onClick={logout}>Logout</button></section></main><Footer/></>;
 return <><Header/><main className="page"><section className="account-card"><h1>Welcome, {profile.name||"Customer"}</h1><h2>My Profile</h2><div className="profile-grid"><div><b>Name</b><span>{profile.name||"—"}</span></div><div><b>Email</b><span>{profile.email||session.user.email||"—"}</span></div><div><b>Phone</b><span>{profile.phone||"Not added"}</span></div><div><b>Address</b><span>{profile.address||"—"}</span></div><div><b>City / District</b><span>{[profile.city,profile.district].filter(Boolean).join(", ")||"—"}</span></div></div><div className="account-edit-card"><h2>Edit Account Details</h2><form className="profile-form" onSubmit={save}><label className="field">Full Name<input value={profile.name||""} onChange={e=>setProfile({...profile,name:e.target.value})} required/></label><label className="field">Email Address<input value={profile.email||session.user.email||""} readOnly/></label><label className="field">Phone Number<input value={profile.phone||""} onChange={e=>setProfile({...profile,phone:e.target.value})} required/></label><label className="field">Delivery Address<textarea rows="3" value={profile.address||""} onChange={e=>setProfile({...profile,address:e.target.value})}/></label><div className="profile-form-row"><label className="field">City<input value={profile.city||""} onChange={e=>setProfile({...profile,city:e.target.value})}/></label><label className="field">District<input value={profile.district||""} onChange={e=>setProfile({...profile,district:e.target.value})}/></label></div><button className="btn" disabled={msg==="Saving…"}>Save Account Details</button>{msg&&<div className="message">{msg}</div>}</form></div><h2>My Orders</h2>{orders.length?orders.map(o=><article className="order-card" key={o.id}><div className="order-head"><strong>{o.order_number||"Order"}</strong><span>{o.order_status||"pending"}</span></div><p>{new Date(o.created_at).toLocaleString()}</p><div className="order-items">{(o.order_items||[]).map((i,n)=><div key={n}>{i.product_name||""}{i.color?" · "+i.color:""}{i.size?" · "+i.size:""} × {i.quantity}</div>)}</div><strong className="order-total">NPR {Number(o.total||0).toLocaleString("en-IN")}</strong><small>Payment: {o.payment_method||"—"} · {o.payment_status||"—"}</small></article>):<p>No orders yet.</p>}<button className="btn secondary" onClick={logout}>Logout</button></section></main><Footer/></>
}
function Home(){return <><Header/><main><section className="hero"><div className="hero-content"><p className="eyebrow">SURU COLLECTION</p><h1>More Than Fashion.<br/><em>It's a Feeling.</em></h1><p>Discover thoughtfully selected traditional and ethnic wear designed to make every occasion feel special.</p><a className="hero-button" href="products.html">Explore Products</a></div></section><section id="collection" className="section"><div className="section-heading"><p className="eyebrow">OUR COLLECTION</p><h2>Made for Every Celebration</h2><p>Explore timeless silhouettes, festive favourites and elegant everyday styles.</p></div><div className="collection-grid">{cats.map(([image,name,description])=><CollectionCard key={name} image={image} name={name} description={description}/>)}</div></section></main><Footer/></>}
function About(){return <><Header/><main><Hero eyebrow="ABOUT SURU COLLECTION" title="Tradition, with a modern feeling." text="Discover the story, inspiration and thoughtful approach behind Suru Collection."/><section className="section story-section"><div className="story-grid"><div className="story-image"><img src="assets/story.jpg" alt="Suru Collection"/></div><div className="story-content"><p className="eyebrow">OUR STORY</p><h2>Tradition, with a modern feeling.</h2><p>Suru Collection brings together beautiful traditional and ethnic wear selected for women who want to celebrate culture while expressing their own style.</p><p>From everyday elegance to festive occasions, every piece is chosen with care, comfort and occasion in mind.</p><p className="story-signature">Inspired by Suruchi Sahani</p></div></div></section></main><Footer/></>}
function Contact(){return <><Header/><main><Hero eyebrow="CONTACT SURU COLLECTION" title="We'd love to hear from you." text="Get in touch for product enquiries, availability, new collections and more."/><section className="section contact-page-section"><div className="contact-grid"><div className="contact-card"><p className="eyebrow">VISIT US</p><h2>Suru Collection</h2><p>Gaur, Rautahat<br/>Nepal</p></div></div></section></main><Footer/></>}
function Products(){return <><Header/><main><Hero eyebrow="SHOP SURU" title="Our Products" text="Explore our complete collection of traditional and ethnic wear."/><section className="section shop-section products-page-section"><ProductsGrid/></section></main><Footer/></>}
function Product(){
 const code=new URLSearchParams(location.search).get("code")||new URLSearchParams(location.search).get("product")||"";
 const[p,setP]=useState(null),[imgs,setImgs]=useState([]),[vars,setVars]=useState([]),[main,setMain]=useState(""),[size,setSize]=useState(""),[colour,setColour]=useState(""),[qty,setQty]=useState(1),[msg,setMsg]=useState(""),[loadErr,setLoadErr]=useState("");
 useEffect(()=>{(async()=>{try{const ps=await get("products",{select:"id,product_code,name,category,description,price,compare_at_price,moq,fabric,color,pattern,is_active",product_code:"eq."+code,is_active:"eq.true"});const x=ps[0];if(!x)throw Error("This product is unavailable.");const [images,variants]=await Promise.all([get("product_images",{select:"image_url,alt_text,is_main,sort_order",product_id:"eq."+x.id,order:"sort_order.asc"}),get("product_sizes",{select:"id,size,color,stock,is_active",product_id:"eq."+x.id,is_active:"eq.true",order:"size.asc"})]);setP(x);setImgs(images||[]);setVars(variants||[]);setMain((images.find(i=>i.is_main)||images[0])?.image_url||"")}catch(e){setLoadErr(e.message)}})()},[code]);
 const sizes=useMemo(()=>[...new Set(vars.map(v=>v.size).filter(Boolean))],[vars]),colours=useMemo(()=>[...new Set(vars.map(v=>v.color).filter(Boolean))],[vars]);
 useEffect(()=>{if(sizes.length===1)setSize(sizes[0]);if(colours.length===1)setColour(colours[0])},[sizes,colours]);
 const variant=useMemo(()=>{if(!vars.length)return null;if(!sizes.length&&!colours.length)return vars.find(v=>!v.size&&!v.color)||vars[0];return vars.find(v=>(!sizes.length||norm(v.size)===norm(size))&&(!colours.length||norm(v.color||p?.color)===norm(colour)))||null},[vars,sizes,colours,size,colour,p]);
 const add=()=>{if(vars.length&&(!variant||Number(variant.stock||0)<=0)){setMsg("Please select an available option.");return}const stock=Number(variant?.stock||0),q=Math.max(1,Math.min(Number(qty)||1,stock||Number(qty)||1));addCart({product_id:p.id,code:p.product_code,name:p.name,price:Number(p.price||0),image:main,size:variant?.size||size||null,color:variant?.color||colour||p.color||null,quantity:q});setMsg("Added to cart successfully.")};
 return <><Header/><main className="product-page">{loadErr?<div className="product-loading-page"><h2>Unable to load product</h2><p>{loadErr}</p></div>:!p?<div className="product-loading-page">Loading product…</div>:<div className="product-layout"><div className="product-gallery"><div className="product-main-image"><img src={main} alt={p.name}/></div>{imgs.length>1&&<div className="product-thumbnails">{imgs.map(i=><button type="button" key={i.image_url} className={main===i.image_url?"product-thumb active":"product-thumb"} onClick={()=>setMain(i.image_url)}><img src={i.image_url} alt={i.alt_text||p.name}/></button>)}</div>}</div><div className="product-info"><div className="product-code">{p.product_code}</div><h1>{p.name}</h1><div className="product-price">{money(p.price)}{p.compare_at_price&&<span className="compare-price">{money(p.compare_at_price)}</span>}</div>{p.description&&<div className="product-description">{p.description}</div>}<div className="product-details">{p.category&&<div><strong>Category:</strong> {p.category}</div>}{p.fabric&&<div><strong>Fabric:</strong> {p.fabric}</div>}{p.color&&<div><strong>Colour:</strong> {p.color}</div>}{p.pattern&&<div><strong>Pattern:</strong> {p.pattern}</div>}{p.moq&&<div><strong>MOQ:</strong> {p.moq}</div>}</div>{colours.length>1&&<label className="field">Colour<select value={colour} onChange={e=>{setColour(e.target.value);setSize("")}}><option value="">Select Colour</option>{colours.map(x=><option key={x}>{x}</option>)}</select></label>}{colours.length===1&&<div className="variant-field"><label>Colour</label><div className="variant-fixed-value">{colours[0]}</div></div>}{sizes.length>0&&<label className="field">Size<select value={size} onChange={e=>setSize(e.target.value)}><option value="">Select Size</option>{sizes.map(x=><option key={x}>{x}</option>)}</select></label>}<label className="field">Quantity<input type="number" min="1" max={variant?.stock||undefined} value={qty} onChange={e=>setQty(e.target.value)}/></label><div className="variant-stock">{variant?variant.stock+" item(s) available":vars.length?"Select an available option.":"Stock information is not configured."}</div>{msg&&<div className="variant-modal-message show">{msg}</div>}<button className="buy-button" type="button" onClick={add}>Add to Cart</button></div></div>}</main><Footer/></>
}

function Order(){
 const[cart,setCart]=useState(()=>readCart()),[name,setName]=useState(""),[phone,setPhone]=useState(""),[address,setAddress]=useState(""),[city,setCity]=useState(""),[payment,setPayment]=useState("Cash on Delivery"),[paymentRef,setPaymentRef]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{const f=()=>setCart(readCart());addEventListener("suruCartChanged",f);return()=>removeEventListener("suruCartChanged",f)},[]);
 useEffect(()=>{(async()=>{try{const{data}=await supabase.auth.getSession();if(!data.session)return;const{data:p}=await supabase.rpc("my_customer_profile");if(p){if(!name)setName(p.name||"");if(!phone)setPhone(p.phone||"");if(!address)setAddress(p.address||"");if(!city)setCity([p.city,p.district].filter(Boolean).join(", "))}}catch{}})()},[]);
 const total=useMemo(()=>cart.reduce((n,x)=>n+Number(x.price||0)*Number(x.quantity??x.qty??0),0),[cart]);
 const remove=item=>setCart(removeCart(item));
 const clear=()=>setCart(clearCart());
 async function place(){if(!cart.length){setMsg("Your cart is empty.");return}if(!name.trim()||!phone.trim()||!address.trim()||!city.trim()){setMsg("Please fill in all delivery details.");return}setBusy(true);setMsg("");try{const{data:userData}=await supabase.auth.getUser();const email=userData?.user?.email||"";const items=cart.map(x=>({code:String(x.code||x.product_code||"").trim(),size:x.size||null,color:x.color||x.colour||null,qty:Math.max(1,Number(x.quantity??x.qty??1))})).filter(x=>x.code);if(!items.length)throw Error("Your cart contains an invalid product. Please remove it and add the product again.");const{data,error}=await supabase.rpc("place_order",{p_customer:{name:name.trim(),phone:phone.trim(),email,address:address.trim(),city:city.trim(),district:null,province:null,postal_code:null},p_items:items,p_payment_method:payment==="Online Payment — confirm with Suru Collection"?"online":"cod",p_customer_note:paymentRef.trim()?"Payment reference: "+paymentRef.trim():null});if(error)throw error;const orderNumber=data?.order_number||"";clear();setMsg(orderNumber?"Order "+orderNumber+" was placed successfully.":"Your order was placed successfully.");}catch(e){setMsg("Unable to place the order. "+(e?.message||"Please try again."))}finally{setBusy(false)}}
 if(!cart.length)return <><Header/><main className="checkout-page"><div className="section-title"><p className="eyebrow">YOUR SHOPPING BAG</p><h1>Your Cart</h1><div className="ornament">⌁◇⌁</div><p>Your cart is empty.</p><a className="hero-btn" href="products.html">Browse Products →</a></div></main><Footer/></>;
 return <><Header/><main className="checkout-page"><div className="section-title"><p className="eyebrow">YOUR SHOPPING BAG</p><h1>Your Cart</h1><div className="ornament">⌁◇⌁</div><p>Review your items and send your order to Suru Collection.</p></div><div className="checkout-grid"><section><div className="cart-items">{cart.map((x,i)=>{const q=Number(x.quantity??x.qty??0);return <article className="cart-item" key={i}>{x.image&&<img src={x.image} alt={x.name||"Product"}/>}<div><small>{x.code||""}</small><h3>{x.name||""}</h3><p>{x.color?"Colour: "+x.color+" · ":""}{x.size?"Size: "+x.size+" · ":""}Qty: {q}</p><strong>{money(Number(x.price||0)*q)}</strong><button className="remove-item" type="button" onClick={e=>{e.preventDefault();e.stopPropagation();remove(x)}}>Remove</button></div></article>})}</div><button className="text-button" type="button" onClick={clear}>Clear Cart</button></section><aside className="order-form"><h2>Delivery Details</h2><p className="form-note">Orders are saved securely and confirmed by Suru Collection before dispatch.</p><label>Full Name<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Your name"/></label><label>Phone Number<input value={phone} onChange={e=>setPhone(e.target.value)} required inputMode="tel" placeholder="98XXXXXXXX"/></label><label>Delivery Address<textarea value={address} onChange={e=>setAddress(e.target.value)} required rows="4" placeholder="House/street, area, Gaur, Rautahat"/></label><label>City / District<input value={city} onChange={e=>setCity(e.target.value)} required placeholder="Gaur, Rautahat"/></label><label>Payment Method<select value={payment} onChange={e=>setPayment(e.target.value)}><option>Cash on Delivery</option><option>Online Payment — confirm with Suru Collection</option></select></label>{payment==="Online Payment — confirm with Suru Collection"&&<div className="online-payment-box"><div className="payment-divider"/><h3>Complete Your Payment</h3><p className="payment-instruction">Scan the QR code below to complete your payment. After payment, you may optionally enter your transaction ID or attach a payment screenshot.</p><div className="payment-qr-wrap"><img src="assets/payment-qr.png" alt="Suru Collection Payment QR Code"/></div><label>Payment Reference / Transaction ID <span className="optional-label">Optional</span><input value={paymentRef} onChange={e=>setPaymentRef(e.target.value)} placeholder="Enter transaction ID if available" autoComplete="off"/></label></div>}<div className="order-total"><span>Total</span><strong>{money(total)}</strong></div><button className="place-order" type="button" onClick={place} disabled={busy}>{busy?"Creating order…":"Place Order"}</button>{msg&&<p className="small-note">{msg}</p>}<p className="small-note">Your order is saved directly to our system. We will confirm your order and delivery details.</p></aside></div></main><Footer/></>;
}

function Admin(){
 const[session,setSession]=useState(null),[authMsg,setAuthMsg]=useState(""),[busy,setBusy]=useState(true),[tab,setTab]=useState("dashboard"),[orders,setOrders]=useState([]),[products,setProducts]=useState([]),[customers,setCustomers]=useState([]),[inventory,setInventory]=useState([]),[stats,setStats]=useState({orders:0,pending:0,products:0}),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[customerSearch,setCustomerSearch]=useState(""),[customerStatus,setCustomerStatus]=useState("all"),[selectedCustomer,setSelectedCustomer]=useState(null),[sourceBranch,setSourceBranch]=useState(()=>localStorage.getItem("suru_ncm_source_branch")||""),[branches,setBranches]=useState([]),[ncmBusy,setNcmBusy]=useState(false),[editing,setEditing]=useState(null),[showAdd,setShowAdd]=useState(false),[message,setMessage]=useState("");
 const adminCheck=async s=>{if(!s?.user?.id)return false;const{data}=await supabase.from("admin_users").select("id,role,is_active").eq("id",s.user.id).maybeSingle();return !!data&&data.is_active&&(data.role==="admin"||data.role==="manager")};
 const refreshDashboard=async()=>{const[a,b,c]=await Promise.all([supabase.from("orders").select("*",{count:"exact",head:true}),supabase.from("products").select("*",{count:"exact",head:true}).eq("is_active",true),supabase.from("orders").select("*",{count:"exact",head:true}).eq("order_status","pending")]);setStats({orders:a.count||0,products:b.count||0,pending:c.count||0});const{data}=await supabase.from("orders").select("id,order_number,customer_name,total,order_status,created_at").order("created_at",{ascending:false}).limit(5);setOrders(data||[])};
 const loadOrders=async()=>{let q=supabase.from("orders").select("*").order("created_at",{ascending:false}).limit(100);if(status)q=q.eq("order_status",status);if(search)q=q.or("order_number.ilike.%"+search+"%,customer_name.ilike.%"+search+"%,customer_phone.ilike.%"+search+"%");const{data,error}=await q;if(error)setMessage(error.message);else setOrders(data||[])};
 const loadProducts=async()=>{const{data,error}=await supabase.from("products").select("*").order("created_at",{ascending:false});if(error)setMessage(error.message);else setProducts(data||[])};
 const loadInventory=async()=>{const{data,error}=await supabase.from("products").select("id,product_code,name,product_sizes(id,size,color,stock,is_active)").order("product_code");if(error)setMessage(error.message);else setInventory(data||[])};
 const loadCustomers=async()=>{const{data,error}=await supabase.rpc("admin_list_customers");if(error)setMessage(error.message);else setCustomers(data||[])};
 useEffect(()=>{(async()=>{try{const{data}=await supabase.auth.getSession();if(!data.session||!(await adminCheck(data.session))){setBusy(false);return}setSession(data.session);await refreshDashboard()}catch(e){setAuthMsg(e.message)}finally{setBusy(false)}})()},[]);
 useEffect(()=>{if(!session)return;if(tab==="dashboard")refreshDashboard();if(tab==="orders")loadOrders();if(tab==="products")loadProducts();if(tab==="inventory")loadInventory();if(tab==="customers")loadCustomers()},[tab,status]);
 async function login(e){e.preventDefault();setAuthMsg("Signing in…");const email=e.target.email.value.trim(),password=e.target.password.value;const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setAuthMsg(error.message);return}if(!(await adminCheck(data.session))){await supabase.auth.signOut();setAuthMsg("This account is not authorized for the admin panel.");return}setSession(data.session);setAuthMsg("");await refreshDashboard()}
 async function logout(){await supabase.auth.signOut();setSession(null)}
 const ncm=async body=>{const{data,error}=await supabase.functions.invoke("ncm-admin",{body});if(error)throw Error(data?.error||error.message);if(data?.error)throw Error(data.error);return data};
 const loadBranches=async()=>{setNcmBusy(true);try{const d=await ncm({action:"branches"});const b=Array.isArray(d)?d:(d?.branches||[]);setBranches(b);setMessage("Loaded "+b.length+" NCM branches.")}catch(e){setMessage("NCM: "+e.message)}finally{setNcmBusy(false)}};
 const updateOrder=async(id,v)=>{const{error}=await supabase.from("orders").update({order_status:v}).eq("id",id);if(error)setMessage(error.message);else loadOrders()};
 const createShipment=async(o)=>{if(!sourceBranch){setMessage("Select the NCM source branch first.");return}const dest=prompt("Enter NCM destination branch",o.city||"");if(!dest)return;if(!confirm("Create this order in Nepal Can Move as a live shipment?"))return;try{const weight=prompt("Enter shipment weight in kg",o.ncm_weight||"1");if(!weight||Number(weight)<=0){setMessage("Enter a valid shipment weight.");return}await ncm({action:"create",order_id:o.id,source_branch:sourceBranch,destination_branch:dest,delivery_type:"Door2Door",weight:String(weight)});setMessage("NCM shipment created successfully.");loadOrders()}catch(e){setMessage("NCM: "+e.message)}};
 const filteredCustomers=customers.filter(c=>{const q=customerSearch.toLowerCase();return(!q||[c.name,c.phone,c.email,c.address,c.city,c.district].filter(Boolean).join(" ").toLowerCase().includes(q))&&(customerStatus==="all"||(customerStatus==="active"&&c.is_active)||(customerStatus==="inactive"&&!c.is_active))});
 const toggleCustomer=async c=>{if(!confirm("Are you sure you want to "+(c.is_active?"deactivate":"activate")+" this customer?"))return;const{error}=await supabase.from("customers").update({is_active:!c.is_active}).eq("id",c.id);if(error)setMessage(error.message);else loadCustomers()};
 async function saveProduct(p){const payload={product_code:p.product_code.trim().toUpperCase(),name:p.name.trim(),category:p.category.trim(),price:Number(p.price),compare_at_price:p.compare_at_price===""?null:Number(p.compare_at_price)||null,moq:Number(p.moq)||0,fabric:p.fabric||null,color:p.color||null,pattern:p.pattern||null,description:p.description||null,is_active:!!p.is_active,is_featured:!!p.is_featured};const{error}=await supabase.from("products").update(payload).eq("id",p.id);if(error)setMessage(error.message);else{setMessage("Product saved.");setEditing(null);loadProducts()}}
 async function addProduct(e){e.preventDefault();const f=e.target;const payload={product_code:f.code.value.trim().toUpperCase(),name:f.name.value.trim(),slug:(f.code.value+"-"+f.name.value).toLowerCase().replace(/[^a-z0-9]+/g,"-"),category:f.category.value.trim(),description:f.description.value.trim()||null,price:Number(f.price.value),moq:Number(f.moq.value)||0,fabric:f.fabric.value.trim()||null,color:f.color.value.trim()||null,pattern:f.pattern.value.trim()||null,is_active:f.active.checked,is_featured:f.featured.checked};const{data:p,error}=await supabase.from("products").insert(payload).select("id").single();if(error){setMessage(error.message);return}const variant={product_id:p.id,size:f.variantSize.value.trim()||null,color:f.variantColor.value.trim()||null,stock:Math.max(0,parseInt(f.initialStock.value||"0",10)),is_active:true};const{error:ve}=await supabase.from("product_sizes").insert(variant);if(ve){await supabase.from("products").delete().eq("id",p.id);setMessage("Product created, but stock setup failed: "+ve.message);return}if(variant.stock)await supabase.from("inventory_movements").insert({product_id:p.id,size_id:(await supabase.from("product_sizes").select("id").eq("product_id",p.id).eq("is_active",true).limit(1).single()).data?.id,quantity_change:variant.stock,reason:"initial_stock"});const urls=f.images.value.split(/\\r?\\n/).map(x=>x.trim()).filter(Boolean);if(urls.length){const{error:ie}=await supabase.from("product_images").insert(urls.map((url,i)=>({product_id:p.id,image_url:url,alt_text:payload.name,sort_order:i,is_main:i===0})));if(ie){setMessage(ie.message);return}}setShowAdd(false);f.reset();loadProducts();loadInventory();setMessage("Product added with stock variant.");}
 async function saveStock(id,productId,value,old){const stock=Math.max(0,parseInt(value||0,10));const{error}=await supabase.from("product_sizes").update({stock}).eq("id",id);if(error){setMessage(error.message);return}const diff=stock-Number(old||0);if(diff)await supabase.from("inventory_movements").insert({product_id:productId,size_id:id,quantity_change:diff,reason:"admin_stock_adjustment"});loadInventory()} async function addVariant(productId){const size=prompt("Variant size (optional)","");if(size===null)return;const color=prompt("Variant colour (optional)","");if(color===null)return;const stock=prompt("Opening stock","0");if(stock===null)return;const n=Math.max(0,parseInt(stock||"0",10));const{data:v,error}=await supabase.from("product_sizes").insert({product_id:productId,size:size.trim()||null,color:color.trim()||null,stock:n,is_active:true}).select("id").single();if(error){setMessage("Unable to add variant: "+error.message);return}if(n)await supabase.from("inventory_movements").insert({product_id:productId,size_id:v.id,quantity_change:n,reason:"initial_stock"});setMessage("Variant added.");loadInventory()}
 async function customerDetails(c){const{data:os}=await supabase.from("orders").select("id,order_number,total,payment_method,payment_status,order_status,created_at").eq("customer_id",c.id).order("created_at",{ascending:false});setSelectedCustomer({...c,orders:os||[]})}
 if(busy)return <div className="admin-page"><div className="login"><div className="login-card"><p>Loading admin panel…</p></div></div></div>;
 if(!session)return <div className="admin-page"><section className="login"><div className="login-card"><img src="assets/suru-logo-official.png" alt="Suru Collection"/><h1>Admin Panel</h1><p>Sign in to manage Suru Collection.</p><form onSubmit={login}><label>Email<input name="email" type="email" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><button className="primary" style={{width:"100%",marginTop:8}}>Sign In</button><div className="message error">{authMsg}</div></form></div></section></div>;
 return <div className="admin-page"><header className="app-header"><div className="brand"><img src="assets/suru-logo-official.png" alt="Suru Collection"/><strong>Admin</strong></div><div className="header-actions"><span className="user-email">{session.user.email}</span><button className="secondary" onClick={logout}>Sign Out</button></div></header><div className="layout"><aside className="sidebar">{[["dashboard","Dashboard"],["orders","Orders"],["products","Products"],["inventory","Inventory"],["customers","Customers"]].map(([v,l])=><button key={v} className={tab===v?"active":""} onClick={()=>setTab(v)}>{l}</button>)}</aside><main className="main">{message&&<div className="message">{message}</div>}
 {tab==="dashboard"&&<><div className="page-title"><div><h2>Dashboard</h2><p>Overview of your online store.</p></div></div><div className="stats"><div className="stat"><small>Total Orders</small><strong>{stats.orders}</strong></div><div className="stat"><small>Pending Orders</small><strong>{stats.pending}</strong></div><div className="stat"><small>Products</small><strong>{stats.products}</strong></div></div><div className="card"><h3>Recent Orders</h3><OrderTable rows={orders.slice(0,5)} compact/></div></>}
 {tab==="orders"&&<><div className="page-title"><div><h2>Orders</h2><p>View customer orders and update their status.</p></div></div><div className="card"><div className="toolbar"><input placeholder="Search order, name or phone" value={search} onChange={e=>setSearch(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{["pending","confirmed","processing","packed","shipped","delivered","cancelled","returned"].map(x=><option key={x}>{x}</option>)}</select><select value={sourceBranch} onChange={e=>{setSourceBranch(e.target.value);localStorage.setItem("suru_ncm_source_branch",e.target.value)}}><option value="">NCM source branch</option>{branches.map((b,i)=><option key={i}>{b.name||b.branch_name||b.title}</option>)}</select><button className="secondary" onClick={loadBranches} disabled={ncmBusy}>Load NCM branches</button></div><OrderTable rows={orders} onStatus={updateOrder} onNcm={createShipment}/></div></>}
 {tab==="products"&&<><div className="page-title"><div><h2>Products</h2><p>Manage product visibility, pricing and featured status.</p></div><button className="primary" onClick={()=>setShowAdd(!showAdd)}>+ Add Product</button></div>{showAdd&&<div className="card"><h3>Add Product</h3><form className="admin-form" onSubmit={addProduct}><div className="form-grid">{[["code","Product Code"],["name","Product Name"],["category","Category"],["price","Price (NPR)"],["moq","MOQ"],["fabric","Fabric"],["color","Colour"],["pattern","Pattern"]].map(([n,l])=><label key={n}>{l}<input name={n} type={n==="price"||n==="moq"?"number":"text"} required={n==="code"||n==="name"||n==="category"||n==="price"}/></label>)}</div><label>Description<textarea name="description" rows="4"/></label><div className="form-grid"><label>Initial Variant Size<input name="variantSize" placeholder="Optional, e.g. M"/></label><label>Initial Variant Colour<input name="variantColor" placeholder="Optional"/></label><label>Initial Stock<input name="initialStock" type="number" min="0" defaultValue="0" required/></label></div><p className="form-note">A stock variant is required for checkout. Leave size/colour blank for products sold as one variant.</p><label>Image URLs<textarea name="images" rows="4" placeholder="One URL per line; first is main image"/></label><div className="check-row"><label><input name="active" type="checkbox" defaultChecked/> Active</label><label><input name="featured" type="checkbox"/> Featured</label></div><button className="primary">Add Product</button></form></div>}<div className="card"><div id="productsGrid">{products.map(p=><ProductAdminCard key={p.id} p={p} editing={editing?.id===p.id} setEditing={setEditing} saveProduct={saveProduct}/>)}</div></div></>}
 {tab==="inventory"&&<><div className="page-title"><div><h2>Inventory</h2><p>Update stock by size.</p></div></div><div id="inventoryGrid">{inventory.map(p=><div className="card" key={p.id}><div className="page-title"><div><h3>{p.product_code} — {p.name}</h3><p>{(p.product_sizes||[]).length} variant(s)</p></div><button className="primary" onClick={()=>addVariant(p.id)}>+ Add Variant</button></div><div className="stock-list">{(p.product_sizes||[]).map(s=><StockRow key={s.id} s={s} productId={p.id} save={saveStock}/>)}</div></div>)}</div></>}
 {tab==="customers"&&<><div className="page-title"><div><h2>Customers</h2><p>View registered customer accounts and their order history.</p></div></div><div className="card"><div className="toolbar"><input placeholder="Search name or phone" value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)}/><select value={customerStatus} onChange={e=>setCustomerStatus(e.target.value)}><option value="all">All customers</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Address</th><th>Status</th><th>Joined</th><th>Actions</th></tr></thead><tbody>{filteredCustomers.map(c=><tr key={c.id}><td>{c.name||"—"}</td><td>{c.phone||"—"}</td><td>{[c.city,c.district].filter(Boolean).join(", ")||c.address||"—"}</td><td><span className={c.is_active?"badge active":"badge inactive"}>{c.is_active?"Active":"Inactive"}</span></td><td>{c.created_at?new Date(c.created_at).toLocaleDateString():"—"}</td><td><button className="secondary" onClick={()=>customerDetails(c)}>View</button> <button className="danger" onClick={()=>toggleCustomer(c)}>{c.is_active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div></div>{selectedCustomer&&<div className="card"><h3>{selectedCustomer.name||"Customer"}</h3><div className="customer-profile-grid">{[["Name",selectedCustomer.name],["Phone",selectedCustomer.phone],["Email",selectedCustomer.email],["Address",selectedCustomer.address],["City",selectedCustomer.city],["District",selectedCustomer.district],["Province",selectedCustomer.province],["Postal Code",selectedCustomer.postal_code]].map(([l,v])=><div key={l}><b>{l}</b><span>{v||"—"}</span></div>)}</div><h3>Order History</h3>{selectedCustomer.orders.length?<table><thead><tr><th>Order</th><th>Date</th><th>Total</th><th>Payment</th><th>Status</th></tr></thead><tbody>{selectedCustomer.orders.map(o=><tr key={o.id}><td>{o.order_number}</td><td>{new Date(o.created_at).toLocaleString()}</td><td>{money(o.total)}</td><td>{o.payment_method||"—"}</td><td>{o.order_status||"—"}</td></tr>)}</tbody></table>:<p>No orders found.</p>}<button className="secondary" onClick={()=>setSelectedCustomer(null)}>Close</button></div>}</>}
 </main></div></div>;
}
function App(){const params=new URLSearchParams(location.search);const page=params.get("page");if(page==="about")return <About/>;if(page==="contact")return <Contact/>;if(page==="products")return <Products/>;if(page==="product")return <Product/>;if(page==="login")return <Login/>;if(page==="register")return <Register/>;if(page==="account")return <Account/>;if(page==="order")return <Order/>;if(page==="admin")return <Admin/>;const p=location.pathname.replace(/\/+$/,"")||"/";if(p.endsWith("/about")||p.endsWith("/about.html"))return <About/>;if(p.endsWith("/contact")||p.endsWith("/contact.html"))return <Contact/>;if(p.endsWith("/products")||p.endsWith("/products.html"))return <Products/>;if(p.endsWith("/product")||p.endsWith("/product.html")||params.has("code")||params.has("product"))return <Product/>;if(p.endsWith("/login")||p.endsWith("/login.html"))return <Login/>;if(p.endsWith("/register")||p.endsWith("/register.html"))return <Register/>;if(p.endsWith("/account")||p.endsWith("/account.html"))return <Account/>;if(p.endsWith("/order")||p.endsWith("/order.html"))return <Order/>;if(p.endsWith("/admin")||p.endsWith("/admin.html"))return <Admin/>;return <Home/>}
createRoot(document.getElementById("root")).render(<App/>);
